services:
#  nginx:
#    env_file: .env
#    image: nginx:alpine
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - openvpn
#    networks:
#      - vpn-network
#    environment:
#      - VPN_DOMAIN=${VPN_DOMAIN}
#    command: >
#      sh -c "
#        envsubst '$$VPN_DOMAIN' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf &&
#        nginx -g 'daemon off;'
#      "

  openvpn:
    env_file: .env
    image: openvpn/openvpn-as
    container_name: openvpn
    devices:
        - /dev/net/tun:/dev/net/tun
    cap_add:
        - NET_ADMIN
        - MKNOD
    ports:
        - 80:80
        - 443:443
        - 1194:1194/udp
    volumes:
      - ./openvpn-data:/openvpn
    restart: unless-stopped
    networks:
      - vpn-network

networks:
  vpn-network: