services:
  csy-bot:
    env_file: .env
    build: .
    container_name: csy-bot
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=${API_URL}
      - API_CERT=${API_CERT}