services:
  csy-bot:
    env_file: ../.env
    container_name: csy-bot
    restart: unless-stopped
    ports:
      - "5001:5001"
    build:
      context: ./
    volumes:
      - ./data:/data
      - ./src:/app/src
    networks:
      - csy-network
networks:
  csy-network:
    external: true