name: csy deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            
            mkdir -p csy
            cd csy
            
            if [ ! -d ".git" ]; then
            echo "Cloning repository..."
            git clone git@github.com:dmitriev-dmitrii/csy.git .
            fi
  
            git fetch origin --depth=1
            git pull --ff-only origin master

            make up
